// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Protocol {
    /// Generic is used to derive keys in the generic derivation scheme
    GenericUnspecified = 0,
    /// SCMP protocol
    Scmp = 1,
}
impl Protocol {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::GenericUnspecified => "PROTOCOL_GENERIC_UNSPECIFIED",
            Self::Scmp => "PROTOCOL_SCMP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PROTOCOL_GENERIC_UNSPECIFIED" => Some(Self::GenericUnspecified),
            "PROTOCOL_SCMP" => Some(Self::Scmp),
            _ => None,
        }
    }
}
