// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EpicDetachedExtension {
    /// Remaining bytes of the full MAC in the hop entry.
    #[prost(bytes = "vec", tag = "1")]
    pub auth_hop_entry: ::prost::alloc::vec::Vec<u8>,
    /// Remaining bytes of the full MAC in the peer entries.
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub auth_peer_entries: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
