// Copyright 2025 Anapaya Systems
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Bindings for [gRPC](https://grpc.io/) types used within the endhost API.
//!
//! The code is autogenerated using prost_build from the protobuf definitions.

pub mod endhost {
    //! Types and services for the endhost API.

    pub mod api_service {
        //! Endhost API service.

        pub mod v1 {
            //! Version 1 of the endhost API service.

            include!("proto/endhost.api_service.v1.rs");
        }
    }
}

pub mod convert;
